# Generated by Django 4.2.30 on 2026-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='category',
            field=models.CharField(default='Fuel', max_length=50),
        ),
    ]
